# Generated by Django 6.0.2 on 2026-08-25 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
        ('products', '0007_alter_productvariant_attributes'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='body',
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='reviews_rev_product_a9ee0d_idx'),
        ),
    ]
