# Generated by Django 6.0.2 on 2026-04-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(verbose_name={'color': 'green', 'size': 'M'}),
        ),
    ]
