# Generated by Django 6.0.2 on 2026-08-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_average_rating_product_review_count'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;"
        )
    ]