# Generated by Django 6.0.2 on 2026-08-29 10:18
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_enable_pg_trgm'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX product_search_gin ON products_product USING GIN (to_tsvector('english', name || ' ' || COALESCE(description, '')));",
            reverse_sql="DROP INDEX IF EXISTS product_search_gin;"
        )
    ]